<?php

/**
 * User
 *
 * PHP version 7.1
 *
 * @package OpenAPIServer\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 */
namespace OpenAPIServer\Model;

use OpenAPIServer\Interfaces\ModelInterface;

/**
 * User
 *
 * @package OpenAPIServer\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */
class User implements ModelInterface
{
    private const MODEL_SCHEMA = <<<'SCHEMA'
{
  "type" : "object",
  "properties" : {
    "id" : {
      "type" : "number"
    },
    "name" : {
      "type" : "string"
    },
    "age" : {
      "type" : "number"
    },
    "data1" : {
      "type" : "string"
    },
    "data2" : {
      "type" : "string"
    },
    "created_at" : {
      "type" : "string"
    },
    "updated_at" : {
      "type" : "string"
    }
  }
}
SCHEMA;

    /** @var float $id */
    private $id;

    /** @var string $name */
    private $name;

    /** @var float $age */
    private $age;

    /** @var string $data1 */
    private $data1;

    /** @var string $data2 */
    private $data2;

    /** @var string $createdAt */
    private $createdAt;

    /** @var string $updatedAt */
    private $updatedAt;

    /**
     * Returns model schema.
     *
     * @param bool $assoc When TRUE, returned objects will be converted into associative arrays. Default FALSE.
     *
     * @return array
     */
    public static function getOpenApiSchema($assoc = false)
    {
        return json_decode(static::MODEL_SCHEMA, $assoc);
    }
}
